### ISSUE TITLE
Requirement is pinned for alarmdecoder 1.13.2: pyserial==2.7

### ISSUE THREAD

**Issue by MartinHjelmare** [ajschmidt8/adext#3]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.
- Please update the alarmdecoder library to minimum version 1.13.9 where the pinning of pyserial has been loosened.

Thanks for your support of Home Assistant!

**Comment by ajschmidt8** [comment]
Hey Martin. Apologies for the late reply. It seems that there is an upstream issue with AlarmDecoder that may prevent us from upgrading. Here are some related PRs/issues for reference:

HA Issue/PR
https://github.com/home-assistant/core/issues/30892
https://github.com/home-assistant/core/pull/31385

Upstream issue that I opened with AlarmDecoder to resolve this:
https://github.com/nutechsoftware/alarmdecoder/issues/47

**Comment by ajschmidt8** [comment]
This issue is closed in [v0.4.0](https://github.com/ajschmidt8/adext/releases/tag/v0.4.0), which uses https://github.com/nutechsoftware/alarmdecoder/commit/d45be9f53884ed21a84fb848b18c17fdfcf86170. There is an open PR in Home Assistant here https://github.com/home-assistant/core/pull/46841.
